### ISSUE TITLE
翻译认领

### ISSUE THREAD

**Issue by jiacai2050** [zigcc/learning-zig#1]
# Table of Contents

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">章节</th>
<th scope="col" class="org-left">翻译</th>
<th scope="col" class="org-left">校对</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">01-installing-zig.md</td>
<td class="org-left">@jiacai2050</td>
<td class="org-left">@sjinzh</td>
</tr>

<tr>
<td class="org-left">02-language-overview-part1.md</td>
<td class="org-left">虫子樱桃</td>
<td class="org-left">夜白</td>
</tr>

<tr>
<td class="org-left">03-language-overview-part2.md</td>
<td class="org-left">夜白</td>
<td class="org-left">虫子樱桃</td>
</tr>

<tr>
<td class="org-left">04-style-guide.md</td>
<td class="org-left">贺鹏</td>
<td class="org-left">@sjinzh</td>
</tr>

<tr>
<td class="org-left">05-pointers.md</td>
<td class="org-left">@sjinzh</td>
<td class="org-left">贺鹏</td>
</tr>

<tr>
<td class="org-left">06-stack-memory.md</td>
<td class="org-left">@fwx5618177</td>
<td class="org-left">@jiacai2050</td>
</tr>

<tr>
<td class="org-left">07-heap-memory-and-allocator.md</td>
<td class="org-left">@fwx5618177</td>
<td class="org-left">@jiacai2050</td>
</tr>

<tr>
<td class="org-left">08-generics.md</td>
<td class="org-left">@jiacai2050</td>
<td class="org-left">贺鹏</td>
</tr>

<tr>
<td class="org-left">09-coding-in-zig.md</td>
<td class="org-left">@jiacai2050</td>
<td class="org-left">贺鹏</td>
</tr>

<tr>
<td class="org-left">10-conclusion.md</td>
<td class="org-left">贺鹏</td>
<td class="org-left">@jiacai2050</td>
</tr>
</tbody>
</table>

有想认领的，可以 issue 留言，或者加入翻译小组微信群，谢谢。

![image](https://github.com/zigcc/learning-zig/assets/3848910/667daf03-7df4-4cc7-9e32-b72835e67e55)

**Comment by czyt** [comment]
我这部分已经翻译

**Comment by fwx5618177** [comment]
06-stack-memory.md
07-heap-memory-and-allocator.md

大体完善了，校对一下吧

**Comment by jiacai2050** [comment]
https://zigcc.github.io/learning-zig

已经完成了！
