### ISSUE TITLE
Windows环境下第十章的示例代码有误

### ISSUE THREAD

**Issue by ccnuu** [zigcc/learning-zig#13]
详细描述我提交了一份到原作者仓库了(尴尬, 当时没注意看是原作者的仓库)

[Windows环境下第十章的示例代码有误](https://github.com/karlseguin/blog/issues/11)

**Comment by jiacai2050** [comment]
Good catch 👍

欢行提交个 PR 修复

**Comment by ccnuu** [comment]
行, 我迟点看看, 这个我先关闭了
