### ISSUE TITLE
第三节 内置数字类型列表缺少 "u47"

### ISSUE THREAD

**Issue by hshq** [zigcc/learning-zig#16]

**Comment by jiacai2050** [comment]
能具体一点嘛？

**Comment by hshq** [comment]
其他一些数字类型有： u8 、 i8 、 u16 、 i16 、 u32 、 i32 、 **_i47_** 、 u64 、 i64 、 f32 和 f64。

包含 **_u47_** 和 **_i47_** 并不是一个确保您仍然清醒的测试;

**Comment by hshq** [comment]
另外，
`const c = b[2...]`
-->
`const c = b[2..]`

**Comment by jiacai2050** [comment]
欢迎直接提 PR 改正。
